services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "3000:3000"
       environment:
         - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://api.id.magiclab.space}
       command: npm run start
       restart: always